# Generated by Django 3.1.7 on 2021-03-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NerSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('info', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='NerSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner_text', models.TextField(blank=True, help_text='text', null=True, verbose_name='text')),
                ('ner_sample', models.JSONField(blank=True, help_text='text', null=True, verbose_name='text')),
                ('ner_ent_exist', models.BooleanField(default=False, verbose_name='Contains Entities')),
                ('ner_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiv.nersource')),
            ],
        ),
    ]
