# Generated by Django 3.2 on 2021-04-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nersample',
            name='ner_ent_type',
            field=models.CharField(blank=True, help_text="',' separated, e.g. PER,LOC", max_length=250, null=True, verbose_name='Entity Types'),
        ),
    ]
